config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats do
    collection do
      get "search", to: "flats#search"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:edit, :update, :show, :destroy]

  def search
    @flats = Flat.where("name LIKE '%#{params[:search]}%'")
  end

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path
  end

  def show
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <br><br><br>
      <%= simple_form_for @flat do |f| %>
        <%= f.input :name, class: "form-control"%>
        <%= f.input :address, class: "form-control"%>
        <%= f.input :description, class: "form-control"%>
        <%= f.input :url, class: "form-control"%>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/edit.html.erb
<%= render 'form' %>

app/views/flats/index.html.erb
<div class="wrpper">
<div class="container">
<h1>All my flats (<%=@flats.count%>)</h1>
  <div class="row">
  <% @flats.each do |flat| %>
    <div class="col-xs-12 col-md-4">


      <div class="card">
        <div class="image" style="background-image: url(<%=flat.url%>)" >
        </div>
        <div class="main-text">
          <h3><%=flat.name%></h3>
          <p><%=flat.address%></p>

        </div>
        <div class = "subtext">
        <i class="fa fa-user a"></i>

          <p><%=flat.number_of_guests%></p>
          <i class="fa fa-eur a"></i>

          <p><%=flat.price_per_night%></p>
        </div>

        <div class="link">
          <%= link_to "More info", flat_path(flat)%>
          <%= link_to "Edit", edit_flat_path(flat)%>
          <%= link_to "Remove", flat_path(flat), method: :delete %>
        </div>

      </div>

    </div>
     <% end %>
  </div>
</div>
</div>

app/views/flats/new.html.erb
<%= render 'form' %>

app/views/flats/search.html.erb
<div class="wrpper">
<div class="container">
<h1>Number of flats found (<%=@flats.count%>)</h1>
  <div class="row">
  <% @flats.each do |flat| %>
    <div class="col-xs-12 col-md-4">


      <div class="card">
        <div class="image" style="background-image: url(<%=flat.url%>)" >
        </div>
        <div class="main-text">
          <h3><%=flat.name%></h3>
          <p><%=flat.address%></p>

        </div>
        <div class = "subtext">
        <i class="fa fa-user a"></i>

          <p><%=flat.number_of_guests%></p>
          <i class="fa fa-eur a"></i>

          <p><%=flat.price_per_night%></p>
        </div>

        <div class="link">
          <%= link_to "More info", flat_path(flat)%>
          <%= link_to "Edit", edit_flat_path(flat)%>
          <%= link_to "Remove", flat_path(flat), method: :delete %>
        </div>

      </div>

    </div>
     <% end %>
  </div>
</div>
</div>

app/views/flats/show.html.erb
<div class="show-wrapper" style="background-image: url(<%=@flat.url%>)">
</div>
<div class="show-content">
  <div class="content-1">
    <div class="conent-left-upper format space">
      <h2><%=@flat.name%></h2>
      <p><%=@flat.address%></p>
    </div>
    <div class="conent-left-under-1 format">
      <h3>A bit more about this flat...</h3>
      <p><%=@flat.description%></p>
      <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=<%=@flat.address%>&zoom=13&scale=1&size=300x300&maptype=roadmap&key=AIzaSyBSiMWYU0I8XUjwo9-gZGxNskGz4OJcQvk&format=png&visual_refresh=true&markers=size:mid%7Ccolor:0xff0000%7Clabel:1%7C<%=@flat.address%>')">
      </div>
    </div>
  </div>

  <div class="content-2">
    <div class="booking format space">
      <h3>Book this place!</h3>
      <div class="input-group">
        <span class="input-group-addon">From:</span>
        <input class="form-control" id="email" name="email" type="text"/>
      </div>
      <div class="input-group">
        <span class="input-group-addon">To:</span>
        <input class="form-control" id="email" name="email" type="text"/>
      </div>
      <input type="submit" name="" class = "btn btn-primary button">
    </div>

    <div class="details format space">
      <h3>Details</h3>
      <div class="icon">
        <i class="fa fa-user a"></i>
        <p><%=@flat.number_of_guests%></p>
        <i class="fa fa-eur a"></i>
        <p><%=@flat.price_per_night%></p>
      </div>
    </div>

    <div class="share format">
      <p>Share</p>
      <div class="logo">
        <i class="fa fa-facebook-square" aria-hidden="true"></i>
        <i class="fa fa-twitter-square" aria-hidden="true"></i>
        <i class="fa fa-pinterest-square" aria-hidden="true"></i>
        <i class="fa fa-envelope" aria-hidden="true"></i>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <%= link_to "Simple Airbnb", flats_path, class: "home"%>
  <form class = "form-inline" action = "/flats/search" method = "get">
    <input type="search" placeholder="Search" name = "search" class = "form-control search">
    <input type="submit" class = "btn btn-primary">
  </form>
  <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Add these line for detecting device width -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

      <%= yield %>


  </body>
</html>